spring.application.name=COMEDOR-UPEU

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/dbcomedorupeu?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USUARIO:root}
spring.datasource.password=${DB_CLAVE:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

app.admin.correo=${ADMIN_CORREO:admin@upeu.edu.pe}
app.admin.clave=${ADMIN_CLAVE}
app.admin.reset=${ADMIN_RESET:false}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

app.upload.dir=uploads/residentes

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
